[project]
name = "queryworkshop25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django-seed>=0.3.1",
    "django>=5.2.3",
    "psycopg2>=2.9.10",
]
